-- ============================================================
-- MAHIR SPEAKING - SUPABASE POSTGRESQL SCHEMA
-- ============================================================

begin;

-- ---------- MASTER TABLES ----------

create table if not exists public.packages (
  id bigint generated by default as identity primary key,
  name varchar(80) not null,
  price integer not null default 0 check (price >= 0),
  period varchar(30) not null default 'monthly',
  ai_daily_limit integer not null default 30,
  tutor_sessions integer not null default 0 check (tutor_sessions >= 0),
  badge varchar(80),
  features jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  full_name varchar(120) not null,
  username varchar(50) not null unique,
  email varchar(255) not null unique,
  whatsapp varchar(30),
  password varchar(255) not null,
  role varchar(20) not null default 'student'
    check (role in ('student', 'tutor', 'admin')),
  admin_type varchar(30),
  package_id bigint references public.packages(id) on delete set null,
  package_expires timestamptz,
  is_trial boolean not null default false,
  xp integer not null default 0 check (xp >= 0),
  points integer not null default 0 check (points >= 0),
  streak integer not null default 0 check (streak >= 0),
  avatar text not null default '/ma.png',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title varchar(160) not null,
  level varchar(50) not null,
  description text,
  tutor_id bigint references public.users(id) on delete set null,
  thumbnail text,
  total_lessons integer not null default 0 check (total_lessons >= 0),
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title varchar(160) not null,
  order_index integer not null,
  video_url text,
  reading_content text,
  target_vocabulary jsonb not null default '[]'::jsonb,
  speaking_prompt text,
  xp_reward integer not null default 50 check (xp_reward between 0 and 1000),
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (course_id, order_index)
);

create table if not exists public.quizzes (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  question text not null,
  options jsonb not null check (jsonb_typeof(options) = 'array'),
  correct_answer integer not null check (correct_answer >= 0),
  xp_reward integer not null default 20 check (xp_reward between 0 and 1000),
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_progress (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  completed boolean not null default false,
  score integer not null default 0 check (score between 0 and 100),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, lesson_id)
);

create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  level varchar(20) not null,
  title varchar(160) not null,
  instruction text not null,
  reference_text text not null,
  translation text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.modules (
  id bigint generated by default as identity primary key,
  title varchar(180) not null,
  type varchar(60) not null default 'PDF Document',
  file_size varchar(30),
  badge varchar(80) default 'Official Modul',
  description text,
  file_url text not null,
  storage_path text,
  is_published boolean not null default true,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recorded_videos (
  id bigint generated by default as identity primary key,
  title varchar(180) not null,
  tutor varchar(120),
  duration varchar(40),
  level varchar(50) not null default 'All Levels',
  video_url text not null,
  thumbnail text,
  is_published boolean not null default true,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.placement_test_leads (
  id bigint generated by default as identity primary key,
  nama varchar(120) not null,
  no_wa varchar(30) not null,
  email varchar(255),
  level_target varchar(30),
  recommended_level varchar(30),
  jadwal_trial timestamptz,
  catatan text,
  status varchar(40) not null default 'Belum Dihubungi',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  package_id bigint not null references public.packages(id) on delete restrict,
  amount integer not null check (amount >= 0),
  payment_method varchar(50) not null default 'QRIS',
  status varchar(30) not null default 'pending'
    check (status in ('pending', 'paid', 'failed', 'expired', 'refunded', 'success')),
  external_reference varchar(150) unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_chats (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  role varchar(20) not null check (role in ('user', 'assistant', 'system')),
  mode varchar(50) not null default 'general',
  content text not null,
  created_at timestamptz not null default now()
);

-- ---------- INDEXES ----------

create index if not exists idx_users_email on public.users (lower(email));
create index if not exists idx_users_username on public.users (lower(username));
create index if not exists idx_lessons_course_order on public.lessons (course_id, order_index);
create index if not exists idx_quizzes_lesson on public.quizzes (lesson_id);
create index if not exists idx_progress_user_lesson on public.user_progress (user_id, lesson_id);
create index if not exists idx_progress_completed on public.user_progress (completed, completed_at desc);
create index if not exists idx_purchases_user on public.purchases (user_id, created_at desc);
create index if not exists idx_ai_chats_user on public.ai_chats (user_id, created_at desc);
create index if not exists idx_leads_status on public.placement_test_leads (status, created_at desc);

-- ---------- AUTOMATIC updated_at ----------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'packages','users','courses','lessons','quizzes','user_progress',
    'exercises','modules','recorded_videos','placement_test_leads','purchases'
  ] loop
    execute format('drop trigger if exists trg_%I_updated_at on public.%I', table_name, table_name);
    execute format(
      'create trigger trg_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',
      table_name, table_name
    );
  end loop;
end $$;

-- ---------- SAFE XP TRANSACTION ----------
-- Signature tetap cocok dengan backend lama. Nilai XP dari client diabaikan;
-- hadiah diambil dari lessons.xp_reward agar user tidak bisa memalsukan XP.

create or replace function public.complete_lesson_secure(
  p_user_id bigint,
  p_lesson_id bigint,
  p_score integer,
  p_xp_reward integer default null
)
returns table (
  progress_id bigint,
  new_xp integer,
  new_points integer,
  new_streak integer,
  status_code varchar
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_progress_id bigint;
  v_completed boolean;
  v_old_score integer;
  v_reward integer;
  v_xp integer;
  v_points integer;
  v_streak integer;
begin
  if not exists (select 1 from public.users where id = p_user_id) then
    return query select 0::bigint, 0, 0, 0, 'USER_NOT_FOUND'::varchar;
    return;
  end if;

  select xp_reward into v_reward
  from public.lessons
  where id = p_lesson_id;

  if v_reward is null then
    v_reward := coalesce(p_xp_reward, 80);
    -- Insert dynamic placeholder lesson to satisfy foreign key constraints
    insert into public.lessons (id, course_id, title, order_index, reading_content, target_vocabulary, speaking_prompt, xp_reward, is_published)
    values (p_lesson_id, 1, 'Unit ' || p_lesson_id || ' Speaking Practice', p_lesson_id, 'Dynamic Reading Content', '[]'::jsonb, 'Dynamic Speaking Prompt', v_reward, true)
    on conflict (id) do nothing;
  end if;

  select id, completed, score
    into v_progress_id, v_completed, v_old_score
  from public.user_progress
  where user_id = p_user_id and lesson_id = p_lesson_id
  for update;

  if coalesce(v_completed, false) then
    update public.user_progress
       set score = greatest(v_old_score, greatest(0, least(100, p_score)))
     where id = v_progress_id;

    select xp, points, streak into v_xp, v_points, v_streak
    from public.users where id = p_user_id;

    return query select v_progress_id, v_xp, v_points, v_streak, 'ALREADY_COMPLETED'::varchar;
    return;
  end if;

  insert into public.user_progress
    (user_id, lesson_id, completed, score, completed_at)
  values
    (p_user_id, p_lesson_id, true, greatest(0, least(100, p_score)), now())
  on conflict (user_id, lesson_id) do update
    set completed = true,
        score = greatest(public.user_progress.score, excluded.score),
        completed_at = now()
  returning id into v_progress_id;

  update public.users
     set xp = xp + v_reward,
         points = points + floor(v_reward / 2.0)::integer,
         streak = streak + 1
    where id = p_user_id
  returning xp, points, streak into v_xp, v_points, v_streak;

  return query select v_progress_id, v_xp, v_points, v_streak, 'SUCCESS'::varchar;
end;
$$;

-- ---------- USEFUL VIEWS ----------

create or replace view public.user_progress_detail as
select
  up.id,
  up.user_id,
  u.full_name,
  u.username,
  up.lesson_id,
  l.title as lesson_title,
  c.title as course_title,
  up.completed,
  up.score,
  up.completed_at
from public.user_progress up
join public.users u on u.id = up.user_id
join public.lessons l on l.id = up.lesson_id
join public.courses c on c.id = l.course_id;

create or replace view public.leaderboard_view as
select
  row_number() over (order by u.xp desc, u.points desc, u.created_at asc) as rank,
  u.id,
  u.full_name,
  u.username,
  u.avatar,
  u.xp,
  u.points,
  u.streak,
  p.name as package_name,
  p.badge as package_badge
from public.users u
left join public.packages p on p.id = u.package_id
where u.role = 'student';

-- ---------- INITIAL DATA ----------

insert into public.packages
  (id, name, price, period, ai_daily_limit, tutor_sessions, badge, features)
values
  (1, 'Kelas Reguler', 350000, 'monthly', 30, 2, 'Reguler',
    '["Akses Kelas Reguler","30 Percakapan AI / hari","Leaderboard Komunitas","Umpan Balik AI Coach"]'::jsonb),
  (2, 'Intermediate', 500000, 'monthly', 100, 4, 'Intermediate',
    '["Akses Kelas Intermediate","100 Percakapan AI / hari","4 Kelas Tatap Muka / bulan","Analisis Pengucapan Detail"]'::jsonb),
  (3, 'Advanced', 750000, 'monthly', -1, 8, 'Advanced',
    '["Akses Kelas Advanced","AI Chat dan Suara Tanpa Batas","8 Kelas Tatap Muka / bulan"]'::jsonb),
  (4, 'Cash Promo (3 Bulan)', 750000, '3 months', -1, 12, 'Best Deal',
    '["Akses Penuh 3 Bulan","12 Kelas Tatap Muka","Sertifikat Kelulusan"]'::jsonb),
  (5, 'Harga Normal (3 Bulan)', 1500000, '3 months', -1, 24, 'Premium Pro',
    '["Akses Penuh 3 Bulan","24 Kelas Tatap Muka","Bimbingan IELTS/TOEFL"]'::jsonb)
on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  period = excluded.period,
  ai_daily_limit = excluded.ai_daily_limit,
  tutor_sessions = excluded.tutor_sessions,
  badge = excluded.badge,
  features = excluded.features;

insert into public.courses
  (id, title, level, description, total_lessons, is_published)
values
  (1, 'Mahir Speaking Starter', 'A1-A2', 'Program belajar speaking dasar sampai percaya diri.', 12, true)
on conflict (id) do update set
  title = excluded.title,
  level = excluded.level,
  description = excluded.description,
  total_lessons = excluded.total_lessons;

insert into public.lessons
  (id, course_id, title, order_index, xp_reward, is_published)
values
  (1, 1, 'Hello! Let''s Introduce Ourselves', 1, 80, true),
  (2, 1, 'My Daily Routine', 2, 80, true),
  (3, 1, 'Family & People Around Me', 3, 90, true),
  (4, 1, 'Food, Drinks & Ordering', 4, 100, true),
  (5, 1, 'Around Town & Directions', 5, 100, true),
  (6, 1, 'Shopping & Making Choices', 6, 110, true),
  (7, 1, 'Plans & Invitations', 7, 110, true),
  (8, 1, 'Past Experiences & Stories', 8, 120, true),
  (9, 1, 'Health & Asking for Help', 9, 120, true),
  (10, 1, 'Study, Work & Responsibilities', 10, 130, true),
  (11, 1, 'Job Interview Basics', 11, 150, true),
  (12, 1, 'Final Speaking Project', 12, 250, true)
on conflict (id) do update set
  course_id = excluded.course_id,
  title = excluded.title,
  order_index = excluded.order_index,
  xp_reward = excluded.xp_reward,
  is_published = excluded.is_published;

-- Rapikan identity setelah memakai ID tetap di seed.
select setval(pg_get_serial_sequence('public.packages', 'id'), greatest((select max(id) from public.packages), 1));
select setval(pg_get_serial_sequence('public.courses', 'id'), greatest((select max(id) from public.courses), 1));
select setval(pg_get_serial_sequence('public.lessons', 'id'), greatest((select max(id) from public.lessons), 1));

-- ---------- SUPABASE STORAGE ----------
-- File modul disimpan sebagai objek, bukan Base64 di tabel/localStorage.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'learning-modules',
  'learning-modules',
  false,
  52428800,
  array[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/zip',
    'audio/mpeg'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- ---------- ROW LEVEL SECURITY ----------
-- Backend Express harus memakai SUPABASE_SERVICE_ROLE_KEY atau koneksi DB server.
-- Jangan pernah meletakkan service role key di frontend.

alter table public.packages enable row level security;
alter table public.courses enable row level security;
alter table public.lessons enable row level security;
alter table public.quizzes enable row level security;
alter table public.exercises enable row level security;
alter table public.modules enable row level security;
alter table public.recorded_videos enable row level security;
alter table public.users enable row level security;
alter table public.user_progress enable row level security;
alter table public.placement_test_leads enable row level security;
alter table public.purchases enable row level security;
alter table public.ai_chats enable row level security;

drop policy if exists "public read packages" on public.packages;
create policy "public read packages" on public.packages for select using (true);

drop policy if exists "public read published courses" on public.courses;
create policy "public read published courses" on public.courses for select using (is_published = true);

drop policy if exists "public read published lessons" on public.lessons;
create policy "public read published lessons" on public.lessons for select using (is_published = true);

-- Jawaban benar tidak dibuka melalui akses publik. Kuis dibaca lewat backend,
-- supaya correct_answer tidak mudah dilihat dari browser.
drop policy if exists "public read quizzes" on public.quizzes;

drop policy if exists "public read exercises" on public.exercises;
create policy "public read exercises" on public.exercises for select using (true);

drop policy if exists "public read published modules" on public.modules;
create policy "public read published modules" on public.modules for select using (is_published = true);

drop policy if exists "public read published videos" on public.recorded_videos;
create policy "public read published videos" on public.recorded_videos for select using (is_published = true);

-- Leads boleh dibuat dari landing page, tetapi tidak boleh dibaca publik.
drop policy if exists "public create placement lead" on public.placement_test_leads;
create policy "public create placement lead"
on public.placement_test_leads for insert
with check (true);

commit;

-- Pemeriksaan akhir (harus menghasilkan 12 lesson).
select id, title, xp_reward from public.lessons order by id;
